### PR TITLE
Minor fixes in the manual

### PR DESCRIPTION
**Pull request by pyxide**
Hi,
the title says it all.
Olivier

### CODE REVIEW

**Comment by ddekany** [comment]
Hi, thanks for the fixes! However, I can only merge them if you have a signed Committer License Agreement at the Apache Software Foundation. You can submit one in e-mail; see here: http://www.apache.org/dev/new-committers-guide.html#cla

**Comment by pyxide** [comment]
I've sent the signed agreement by email. It was much more work than my pull request, I had to rip some code from stackoverflow to compose the PDF document with the scans!
I'll keep you posted.

**Comment by ddekany** [comment]
Apache has received your CLA, so I will be able to merge this now (and BTW now you can contribute to any other Apache projects as well). As of the PDF issues, you are supposed to print the thing as is, fill it by hand, scan the whole page, and save the resulting single big image into a PDF. So no special software is needed.

**Comment by pyxide** [comment]
Thank you for the follow-up and the information.

**Pull request merged**
