### PR TITLE
FREEMARKER-55: Renaming Freemarker to FreeMarker

### PR DESCRIPTION
**Pull request by woonsan**

### CODE REVIEW

**Comment by woonsan** [comment]
This time, I'll try to merge this by myself as this is trivial. :-)

**Comment by ddekany** [comment]
Your merge did not close this PR though. Certainly because the message didn't contain the usual "Merge commit 'refs/pull/${N}/head' of https://github.com/apache/incubator-freemarker into 3" thing. (I do it like this: http://freemarker.org/committer-howto.html#merging-pull-request)

**Comment by ddekany** [comment]
Hm... I can't even close it. Can you? I did like http://freemarker.org/committer-howto.html#close-pull-request-without-merging, and this has worked earlier, but not in this case.

**Comment by woonsan** [comment]
On Sat, Jul 15, 2017 at 6:18 PM, ddekany <notifications@github.com> wrote:

> Hm... I can't even close it. Can you? I did like http://freemarker.org/
> committer-howto.html#close-pull-request-without-merging, and this has
> worked earlier, but not in this case.
>
I'm sorry for not following the guideline on how to close PR in the
documentation. I'll keep that in mind next time.
I can't close it myself either. When pushing after executing "git commit
--allow-empty -m "closes apache/incubator-freemarker#28: Already merged so
closing PR without merging.", I got the following error:

remote: You are not authorized to edit this repository.
remote:
To https://git-wip-us.apache.org/repos/asf/incubator-freemarker.git
 ! [remote rejected] 3 -> 3 (pre-receive hook declined)
error: failed to push some refs to '
https://git-wip-us.apache.org/repos/asf/incubator-freemarker.git'

If nothing happens, I'll close the PR manually this time later.

Thanks,

Woonsan

**Comment by ddekany** [comment]
The authorization issue is a different thing. I can't push anything to any of the FM repos for about 24 hours now. Seems this also affects you. I have opened an issue for it (https://issues.apache.org/jira/servicedesk/customer/portal/1/INFRA-14602), but then I add that you can't push either.

And how can you close it "manually"?

**Comment by ddekany** [comment]
Now you should have right to do a Git push again.

**Comment by woonsan** [comment]
On Sun, Jul 16, 2017 at 2:58 PM, ddekany <notifications@github.com> wrote:

> The authorization issue is a different thing. I can't push anything to any
> of the FM repos for about 24 hours now. Seems this also affects you. I have
> opened an issue for it (https://issues.apache.org/
> jira/servicedesk/customer/portal/1/INFRA-14602), but then I add that you
> can't push either.
>
I've just pushed successfully. Thanks a lot!
I'll wait until tomorrow. Not automatically closed, I'll probably close it
manually through github UI.

> And how can you close it "manually"?
>
The author, not others, can close his or her pull request through github UI
("Close pull request" button).

Regards,

Woonsan

**Comment by woonsan** [comment]
Closing this PR manually as it was already merged.

**Pull request closed without merging**
